
// services/CommandGuard.ts

export interface SecurityAudit {
  isSafe: boolean;
  riskLevel: 'LOW' | 'MEDIUM' | 'CRITICAL';
  flags: string[];
  sanitizedCommand: string;
}

// Dangerous binaries that trigger immediate intervention
const BINARY_BLOCKLIST = [
  'nc', 'netcat', 'ncat', // Reverse shells
  'curl', 'wget',         // Data exfiltration
  'bash', 'sh', 'zsh',    // Shell execution
  'sudo', 'su',           // Privilege escalation
  'chmod', 'chown',       // Permission changes
  'dd', 'mkfs', 'fdisk'   // Disk destruction
];

// Patterns indicating obfuscation or malicious chaining
const DANGEROUS_PATTERNS = [
  /\|\s*bash/i,           // Pipe to bash
  /\|\s*sh/i,             // Pipe to sh
  />\s*\/dev\/null/i,     // Hiding output (common in malware)
  /`.*`/,                 // Backtick execution
  /\$\(.*\)/,             // Subshell execution
  /\/etc\/shadow/,        // Sensitive file access
  /\.ssh/                 // SSH key access
];

/**
 * Audits a shell command generated by AI before it is rendered or executed.
 */
export const auditShellCommand = (command: string): SecurityAudit => {
  const audit: SecurityAudit = {
    isSafe: true,
    riskLevel: 'LOW',
    flags: [],
    sanitizedCommand: command
  };

  if (!command) return audit;

  const trimmed = command.trim();
  const tokens = trimmed.split(/\s+/);
  const baseBinary = tokens[0]?.toLowerCase();

  // 1. Check Binary Blocklist
  if (BINARY_BLOCKLIST.includes(baseBinary)) {
    audit.isSafe = false;
    audit.riskLevel = 'CRITICAL';
    audit.flags.push(`BLOCKED_BINARY: ${baseBinary}`);
  }

  // 2. Check Dangerous Patterns
  DANGEROUS_PATTERNS.forEach((pattern) => {
    if (pattern.test(trimmed)) {
      audit.isSafe = false;
      audit.riskLevel = 'CRITICAL';
      audit.flags.push(`DANGEROUS_PATTERN: ${pattern.toString()}`);
    }
  });

  // 3. Heuristic: Destructive Flags
  if (trimmed.includes('rm -rf') || trimmed.includes('rm -r')) {
    audit.isSafe = false;
    audit.riskLevel = 'CRITICAL';
    audit.flags.push('RECURSIVE_DELETION_DETECTED');
  }

  // 4. Heuristic: Unmasked Network Activity
  if ((trimmed.includes('http://') || trimmed.includes('https://')) && !BINARY_BLOCKLIST.includes(baseBinary)) {
    audit.riskLevel = 'MEDIUM';
    audit.flags.push('EXTERNAL_NETWORK_REQUEST');
  }

  return audit;
};
