
// services/scraperService.ts
import { ScrapedPayload, KnowledgeSource } from '../types/refinery';
import { appEventBus } from '../lib/eventBus';

/**
 * HEADLESS BROWSER BRIDGE
 * Interfaces with external Puppeteer/Playwright services for SPA hydration.
 */
class HeadlessBrowserBridge {
  private endpoint: string = 'https://proxy.aether-shunt.io/render';

  public async fetchHydrated(url: string): Promise<string> {
    appEventBus.emit('telemetry', {
      type: 'system_action',
      data: { eventType: 'headless_render_init', target: url }
    });

    // Architecture Note: In a production environment, this would be a POST to a specialized worker.
    // For local simulation, we simulate the hydration delay and DOM processing.
    await new Promise(r => setTimeout(r, 2500)); 

    return `
      <div id="root">
        <header>SPA Hydrated via Headless Bridge</header>
        <main>
          <article>
            <h1>Client-Side Rendered Data</h1>
            <p>This content was generated by JavaScript after initial load.</p>
          </article>
        </main>
      </div>
    `;
  }
}

class ProxyRotationEngine {
  private proxies = [
    { id: 'us-east-1', ip: '162.158.12.44', provider: 'Residential' },
    { id: 'eu-west-1', ip: '185.22.144.12', provider: 'DataCenter' },
    { id: 'ap-south-1', ip: '103.21.244.0', provider: 'Residential' },
    { id: 'br-latam-1', ip: '177.10.155.99', provider: 'Mobile' }
  ];
  private currentIndex = 0;

  public getNextProxy() {
    const proxy = this.proxies[this.currentIndex];
    this.currentIndex = (this.currentIndex + 1) % this.proxies.length;
    return proxy;
  }

  public getProxyHeaders() {
    const proxy = this.getNextProxy();
    return {
      'X-Proxy-Node': proxy.id,
      'X-Forwarded-For': proxy.ip,
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    };
  }
}

class DOMSanitizer {
  private blacklistedTags = ['script', 'style', 'link', 'iframe', 'svg', 'canvas', 'video', 'audio', 'noscript', 'meta'];

  public sanitize(html: string): string {
    if (!html) return '';
    let clean = html;
    this.blacklistedTags.forEach(tag => {
      const regex = new RegExp(`<${tag}[^>]*>[\\s\\S]*?<\\/${tag}>`, 'gi');
      clean = clean.replace(regex, '');
    });
    clean = clean.replace(/<!--[\s\S]*?-->/g, '');
    clean = clean.replace(/<([a-z1-6]+)\s+[^>]*>/gi, (match, tag) => {
        const hrefMatch = match.match(/href="([^"]*)"/i);
        return hrefMatch ? `<${tag} ${hrefMatch[0]}>` : `<${tag}>`;
    });
    clean = clean.replace(/\s+/g, ' ').trim();
    return clean;
  }
}

class ScraperService {
  private proxyEngine = new ProxyRotationEngine();
  private sanitizer = new DOMSanitizer();
  private headlessBridge = new HeadlessBrowserBridge();

  async fetchRawHtml(url: string, useHeadless: boolean = false): Promise<string> {
    if (useHeadless) {
      return await this.headlessBridge.fetchHydrated(url);
    }

    const headers = this.proxyEngine.getProxyHeaders();
    appEventBus.emit('telemetry', {
      type: 'system_action',
      data: {
        eventType: 'network_request',
        interactionType: 'proxy_rotation',
        tab: 'Network',
        contextDetails: { target: url, proxyNode: headers['X-Proxy-Node'] }
      }
    });

    await new Promise(resolve => setTimeout(resolve, 1200));
    return `<html><body><h1>Static Scrape Results for ${url}</h1></body></html>`;
  }

  cleanDom(rawHtml: string): string {
    const startSize = rawHtml.length;
    const sanitized = this.sanitizer.sanitize(rawHtml);
    const endSize = sanitized.length;
    const compression = Math.round(((startSize - endSize) / startSize) * 100);

    appEventBus.emit('telemetry', {
      type: 'system_action',
      data: {
        eventType: 'data_processing',
        interactionType: 'dom_sanitization',
        tab: 'Refinery',
        contextDetails: { originalBytes: startSize, sanitizedBytes: endSize, tokenSavings: `${compression}%` }
      }
    });

    return sanitized;
  }

  async deepCrawl(startUrl: string): Promise<string> {
      const raw = await this.fetchRawHtml(startUrl, true); // Deep crawl forces headless hydration
      const clean = this.cleanDom(raw);
      return `# HEADLESS EXTRACTION COMPLETE\n**Target:** ${startUrl}\n**Mode:** SPA Hydration Enabled\n---\n${clean}`;
  }
}

export const scraperService = new ScraperService();
